hack: pin home-manager to known working version
Something weird is going on. Docs are failing to build. This commit
allows me to at least update to a recent version of home-manager and
use my normal update system while the flake revision is pinned.

I need to look into this over the next week days when I'm not so bust
and open up an upstream issue if this isn't something going on locally.

Also needed to rollback the changes to firefox module to move back from
profile support. No bigge, just my secondary browser anyway.

```diff
diff --git i/flake.nix w/flake.nix
index 1bb4df4..e4a7a11 100644
--- i/flake.nix
+++ w/flake.nix
@@ -2,7 +2,9 @@
   inputs = {
     nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable-small";
     nixos-hardware.url = "github:NixOS/nixos-hardware/";
-    home-manager.url = "github:nix-community/home-manager/176e455371a8371586e8a3ff0d56ee9f3ca2324e";
+    # TODO: this commit breaks building docs?
+    # https://github.com/nix-community/home-manager/commit/2827b5306462d91edec16a3d069b2d6e54c3079f
+    home-manager.url = "github:nix-community/home-manager/2827b5306462d91edec16a3d069b2d6e54c3079f";
     nix-darwin.url = "github:LnL7/nix-darwin";
     pre-commit-hooks.url = "github:cachix/pre-commit-hooks.nix";
     nur.url = "github:nix-community/NUR";

```

This is the error when building with the broken commit.

```
darwin-rebuild  --flake .#DCP40KQJX6 build --keep-going
warning: Git tree '/Users/kyle.ondy/src/dotfiles' is dirty
warning: updating lock file '/Users/kyle.ondy/src/dotfiles/flake.lock':
• Updated input 'home-manager':
    'github:nix-community/home-manager/176e455371a8371586e8a3ff0d56ee9f3ca2324e' (2023-01-10)
  → 'github:nix-community/home-manager/2827b5306462d91edec16a3d069b2d6e54c3079f' (2023-01-14)
warning: Git tree '/Users/kyle.ondy/src/dotfiles' is dirty
building the system configuration...
warning: Git tree '/Users/kyle.ondy/src/dotfiles' is dirty
error: builder for '/nix/store/qyqkkp0xpj8w8f80zw6k0978bb2dy3l9-manual-combined.drv' failed with exit code 3;
       last 10 log lines:
       > /nix/store/47h9wc7qd3v9c96i48bp7dh72dwp2y46-manual-combined/manual-combined.xml:1400: element listitem: Relax-NG validity error : Did not expect element listitem there
       >   1396        not bound to an attribute.</simpara>
       >   1397    <simpara>Some arguments are already passed by default, of which the
       >   1398     following <emphasis>cannot</emphasis> be changed with this option:</simpara>
       >   1399    <itemizedlist>
       >   1400  <listitem><para><simpara><varname>lib</varname>: The nixpkgs library.</simpara>
       >   1401 </para></listitem>
       >   1402      <listitem><para><simpara><varname>config</varname>: The results of all options after merging the values from all modules together.</simpara>
       >
       > /nix/store/47h9wc7qd3v9c96i48bp7dh72dwp2y46-manual-combined/manual-combined.xml fails to validate
       For full logs, run 'nix log /nix/store/qyqkkp0xpj8w8f80zw6k0978bb2dy3l9-manual-combined.drv'.
error: 1 dependencies of derivation '/nix/store/9ca1k7q6cr6gygwwh5j26r8a3ybg2j6d-manual-olinkdb.drv' failed to build
error: 2 dependencies of derivation '/nix/store/54k5n0l6xawg80167f8205s9fwp8hajh-man-pages.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7jh4lxjdw7gf9mjyy7x7l6bmswxkblav-home-manager-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cdm6r3p4lp871argc12jknkzp2ghzi33-home-manager-fonts.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q7z0v5a39z2l009sdcyzlhp89sl12p27-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lpiw84z0jc13jpx16yn28ld7jdna7j4d-activation-script.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cqipcs0jh1ws69kh1c2ch84ddjvgh37m-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zvkjndli4429dkn2gpp57jgmvcnd2c33-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/brfx92kr65dcrfdjjrrdiqbh5cgy247h-etc.drv' failed to build
error: 3 dependencies of derivation '/nix/store/6khizw06f727wllxymbxg7x0kv4varp0-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xvdv8jgxl3qzivfi2g9pnich6pxbyx1r-activation-kyle.ondy.drv' failed to build
error: 2 dependencies of derivation '/nix/store/ghmw1wh3kx34k939g62hgls1z4615g2y-darwin-system-22.11.20221117.3a86856+darwin4.87b9d09.drv' failed to build
make: *** [Makefile:30: build] Error 1
```